furniture_shop_backend/api/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from .views import ProductViewSet, ProductMoreDetailView, comment_CR_api

router = SimpleRouter()
router.register(r'store', ProductViewSet, basename='store')

app_name = "api"

urlpatterns = [
    *router.urls,
    path('comment/', comment_CR_api, name='comment'),
    path('detail/<int:pk>/', ProductMoreDetailView.as_view()),
]

furniture_shop_backend/cart/urls.py
from django.urls import include, path

from cart.views import cart_add, cart_view, cart_sub, cart_del, cart_clear

app_name = "cart"

urlpatterns = [
    path("add/<int:pk>/", cart_add, name="cart_add"),
    path("sub/<int:pk>/", cart_sub, name="cart_sub"),
    path("del/<int:pk>/", cart_del, name="cart_del"),
    path("clear/", cart_clear, name="cart_clear"),
    path("", cart_view, name="cart_view"),
]

furniture_shop_backend/furniture_shop/urls.py
from django.contrib import admin
from django.urls import include, path
from advuser.views import EmailLoginView
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.contrib.staticfiles.views import serve


urlpatterns = [
    path("admin/login/", EmailLoginView.as_view(template_name="advuser/admin-login.html")),
    path("admin/", admin.site.urls),
    path("auth/", include('advuser.urls')),
    path("cart/", include('cart.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path("api/", include('api.urls')),
    path('captcha/', include('captcha.urls')),
    path("", include('main.urls')),
]


if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve))) # Запрет на кеширование статики
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

furniture_shop_backend/main/urls.py
from django.urls import include, path

from .views import (any_page, IndexPageView, DetailPageView, 
                        CategoryPageView, 
                        favorite_toggle, FavoriteProductsView,
                        product_create_view,
                        product_edit_view,
                        product_del_view)


app_name = "main"

urlpatterns = [
    path("product/<int:pk>/", DetailPageView.as_view(), name="detail"),
    path("category/<int:pk>/", CategoryPageView.as_view(), name="category"),
    path("add/", product_create_view, name="product_create"),
    path("edit/<int:pk>/", product_edit_view, name="product_edit"),
    path("delete/<int:pk>/", product_del_view, name="product_delete"),
    path("favorite/<int:pk>/", favorite_toggle, name="favorite_toggle"),
    path("favorite/", FavoriteProductsView.as_view(), name="favorite_products"),
    path("<str:url>/", any_page, name="any_page"),
    path("", IndexPageView.as_view(), name="index"),
]

furniture_shop_backend/cart/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect

from main.models import Product
from .cart import Cart


def cart_view(request):
    return render(request, 'cart/cart.html')


def cart_add(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=pk)

    cart.add(product)
    if (path := request.META.get('HTTP_REFERER')):
        return redirect(path)
    else:
        return redirect('cart:cart_view')


def cart_sub(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=pk)

    cart.add(product, -1)
    if (path := request.META.get('HTTP_REFERER')):
        return redirect(path)
    else:
        return redirect('cart:cart_view')


def cart_del(request, pk):
    cart = Cart(request)
    cart.delete(pk)
    if (path := request.META.get('HTTP_REFERER')):
        return redirect(path)
    else:
        return redirect('cart:cart_view')


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    if (path := request.META.get('HTTP_REFERER')):
        return redirect(path)
    else:
        return redirect('cart:cart_view')

furniture_shop_backend/cart/templates/cart/cart.html
{% extends 'layout/base.html' %}

{% load static %}
{% load bootstrap5 %}

{% block title %}
Корзина
{% endblock title %}

{% block content %}

<div class="d-inline-block">

<h3>Товары в вашей корзине</h3>


<div class="btn-group my-3" role="group" aria-label="Basic outlined example">
    {% url 'cart:cart_clear' as url_cart_clear %}
    {% bootstrap_button "Оформить заказ" button_type="link" button_class="btn-outline-primary" %}
    {% bootstrap_button "Очистить корзину" button_type="link" button_class="btn-outline-primary" href=url_cart_clear %}
  </div>

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Товар</th>
        <th scope="col">Фото</th>
        <th scope="col">Количество</th>
        <th scope="col">Цена</th>
        <th scope="col">Валюта</th>
        <th scope="col">Сумма</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>

{% for item in cart %}

<tr>
    <th scope="row">{{ forloop.counter }}</th>
    <td>
      <a href="{% url 'main:detail' pk=item.product.pk %}">
        {{ item.product.title }}
      </a>
    </td>
    <td>
      <a href="{% url 'main:detail' pk=item.product.pk %}">
        {% if item.product.image %}
        <img src="{{ item.product.image.url }}" class="img-fluid rounded-start main-image">
        {% else %}
        <img src="{% static image_stub %}" class="img-fluid rounded-start main-image">
        {% endif %}
    </a>
</td>
    <td>{{ item.count }}</td>
    <td>{{ item.price }}</td>
    <td>руб.</td>
    <td>{{ item.total_price}}</td>
    <td>
        {% url 'cart:cart_add' item.product.id as url_cart_add %}
        {% url 'cart:cart_del' item.product.id as url_cart_del %}
        {% bootstrap_button "+1" button_type="link" href=url_cart_add size="small" %}
        {% if item.count > 1 %}
        {% url 'cart:cart_sub' item.product.id as url_cart_sub %}
        {% bootstrap_button "-1" button_type="link" href=url_cart_sub size="small" %}
        {% else %}
        {% bootstrap_button "-1" button_type="link" href=url_cart_del size="small" %}
        {% endif %}
        {% bootstrap_button "Удалить" button_type="link" href=url_cart_del size="small" %}
    </td>
  </tr>

{% endfor %}

<tr>
    <th scope="row"></th>
    <td>Всего</td>
    <td colspan=4></td>
    <td>{{ cart.get_total_price }}</td>
    <td>{% bootstrap_button "Очистить корзину" button_type="link" href=url_cart_clear %}</td>
  </tr>
</tbody>
</table>

{% endblock content %}