furniture_shop_backend/api/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from .views import ProductViewSet, ProductMoreDetailView, comment_CR_api

router = SimpleRouter()
router.register(r'store', ProductViewSet, basename='store')

app_name = "api"

urlpatterns = [
    *router.urls,
    path('comment/', comment_CR_api, name='comment'),
    path('detail/<int:pk>/', ProductMoreDetailView.as_view()),
]

furniture_shop_backend/cart/urls.py
from django.urls import include, path

from cart.views import cart_add, cart_view, cart_sub, cart_del, cart_clear

app_name = "cart"

urlpatterns = [
    path("add/<int:pk>/", cart_add, name="cart_add"),
    path("sub/<int:pk>/", cart_sub, name="cart_sub"),
    path("del/<int:pk>/", cart_del, name="cart_del"),
    path("clear/", cart_clear, name="cart_clear"),
    path("", cart_view, name="cart_view"),
]

furniture_shop_backend/furniture_shop/urls.py
from django.contrib import admin
from django.urls import include, path
from advuser.views import EmailLoginView
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.contrib.staticfiles.views import serve


urlpatterns = [
    path("admin/login/", EmailLoginView.as_view(template_name="advuser/admin-login.html")),
    path("admin/", admin.site.urls),
    path("auth/", include('advuser.urls')),
    path("cart/", include('cart.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path("api/", include('api.urls')),
    path('captcha/', include('captcha.urls')),
    path("", include('main.urls')),
]


if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve))) # Запрет на кеширование статики
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

furniture_shop_backend/main/urls.py
from django.urls import include, path

from .views import (any_page, IndexPageView, DetailPageView, 
                        CategoryPageView, 
                        favorite_toggle, FavoriteProductsView,
                        product_create_view,
                        product_edit_view,
                        product_del_view)


app_name = "main"

urlpatterns = [
    path("product/<int:pk>/", DetailPageView.as_view(), name="detail"),
    path("category/<int:pk>/", CategoryPageView.as_view(), name="category"),
    path("add/", product_create_view, name="product_create"),
    path("edit/<int:pk>/", product_edit_view, name="product_edit"),
    path("delete/<int:pk>/", product_del_view, name="product_delete"),
    path("favorite/<int:pk>/", favorite_toggle, name="favorite_toggle"),
    path("favorite/", FavoriteProductsView.as_view(), name="favorite_products"),
    path("<str:url>/", any_page, name="any_page"),
    path("", IndexPageView.as_view(), name="index"),
]

furniture_shop_backend/main/forms.py
from django import forms
from captcha.fields import CaptchaField

from main.models import (Product, AdditionalImage,
                         SuperCategory, SubCategory, 
                         CharacteristicGroup, CharacteristicItem, CharacteristicProductRelated,
                         Comment)


class SubCategoryForm(forms.ModelForm):
    group = forms.ModelChoiceField(queryset=SuperCategory.objects.all(),
                                   empty_label=None,
                                   label='группа категорий',
                                   required=True)
    
    class Meta:
        model = SubCategory
        fields = '__all__'


class CharacteristicItemForm(forms.ModelForm):
    group = forms.ModelChoiceField(queryset=CharacteristicGroup.objects.all(),
                                   empty_label=None,
                                   label='группа характеристик',
                                   required=True)
    
    class Meta:
        model = CharacteristicItem
        fields = '__all__'


class UserCommentBaseForm(forms.ModelForm):
    # author = forms.CharField(label='Автор', disabled=True)
    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'product': forms.HiddenInput,
                   'author': forms.TextInput(attrs={'readonly': True})}
        help_texts = {'is_claim': "Сообщения, содержащие жалобы, направляются в службу контроля качества"}

    def clean(self):
        author_name = self.cleaned_data['author']
        if self.cleaned_data.get('is_anonimous'):
            self.cleaned_data['author'] = self._meta.model.ANONIMOUS_NAME


class UserCommentForm(UserCommentBaseForm):
    pass
        
class GuestCommentForm(UserCommentBaseForm):
    captcha = CaptchaField(label='введите код с картинки',
                           error_messages = {'invalid': 'Неправильный текст'})

    class Meta(UserCommentBaseForm.Meta):
        exclude = ('is_active', 'is_anonimous')


class CreateProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'title', 'description', 'count', 'price', 'image')

class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'title', 'description', 'count', 'price', 'is_active', 'image')


class AdditionalImageForm(forms.ModelForm):
    class Meta:
        model = AdditionalImage
        fields = '__all__'
        widgets = {'product': forms.HiddenInput}

    def clean(self):
        super().clean()
        errors = {}
        if self.cleaned_data['image'] and not self.cleaned_data['product'].image:
            errors['image'] = forms.ValidationError("Не выбрано основное изображение")
        if errors:
            raise forms.ValidationError(errors)

AdditionalImageFormSet = forms.inlineformset_factory(Product, AdditionalImage, form=AdditionalImageForm, extra=3, can_delete=False)

class SelectCharacteristicForm(forms.ModelForm):
    class Meta:
        model = CharacteristicProductRelated
        fields = ('characteristic', 'value', 'product')
        widgets = {'product': forms.HiddenInput}

SelectCharacteristicFormSet = forms.inlineformset_factory(Product, 
                                                          CharacteristicProductRelated, 
                                                          form=SelectCharacteristicForm, 
                                                          extra=3, 
                                                          can_delete=False)

furniture_shop_backend/main/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.http.response import HttpResponseNotFound
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.db.models.query import Prefetch
from django.db.models import F, Q, Case, When, BooleanField
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from main.utilities import user_is_staff, user_permission_test

from .models import (Product, 
                     CharacteristicItem, 
                     Category, 
                     AdditionalImage, 
                     UserProductRelated, 
                     Comment)
from .forms import (UserCommentForm, 
                    GuestCommentForm, 
                    CreateProductForm, 
                    EditProductForm, 
                    AdditionalImageFormSet, 
                    SelectCharacteristicFormSet)


class IndexPageView(ListView):
    prefetch_characteristics = Prefetch('characteristics',
                        queryset=(CharacteristicItem.objects
                                  .annotate(value=F('characteristicproductrelated__value'))
                                  .select_related('group',)
                                  .distinct()
                                  ),
                        to_attr="characts_to_public"
                        )

    queryset = (Product.objects
                .select_related('category')
                .filter(is_active__exact=True)
                .defer('is_active', 'created_at', 'changed_at')
                .prefetch_related(prefetch_characteristics)
    )
    template_name = "main/index.html"
    context_object_name = 'store'
    paginate_by = 2

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return (super().get_queryset()
                          .annotate(favorite=Case(
                            When(id__in=self.request.user.userproductrelated_set.filter(is_favorit__exact=True).values('product__id'), then=True),
                            default=False,
                            output_field=BooleanField()
                          ))
            )
        return super().get_queryset()


class CategoryPageView(IndexPageView):
    def get_queryset(self):
        cat_id = self.kwargs['pk']
        return super().get_queryset().filter(Q(category_id__exact=cat_id) | Q(category__super_category_id__exact=cat_id))
                                             
    def get_context_data(self, **kwargs):
        category_queryset = Category.objects.filter(id__exact=self.kwargs['pk'])
        if category_queryset.exists():
            kwargs['category'] = category_queryset.get().title
        else:
            raise Http404

        return super().get_context_data(**kwargs)
   

class DetailPageView(DetailView):
    CONTEXT_OBJECT_NAME = 'item'
    prefetch = Prefetch('characteristics',
                        queryset=(CharacteristicItem.objects
                                  .annotate(value=F('characteristicproductrelated__value'))
                                  .select_related('group',)
                                  .distinct()
                                  ),
                        to_attr="characts_to_public"
                        )
    queryset =   queryset = (Product.objects
                .select_related('category')
                .filter(is_active__exact=True)
                .defer('is_active', 'created_at', 'changed_at')
                .prefetch_related(prefetch)
    )
    context_object_name = CONTEXT_OBJECT_NAME
    template_name = "main/detail.html"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return (super().get_queryset()
                          .annotate(favorite=Case(
                            When(id__in=self.request.user.userproductrelated_set.filter(is_favorit__exact=True).values('product__id'), then=True),
                            default=False,
                            output_field=BooleanField()
                          ))
            )
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        images = AdditionalImage.objects.filter(product=context[self.CONTEXT_OBJECT_NAME].pk)
        context['additional_images'] = images

        comments = Comment.objects.filter(product=context[self.CONTEXT_OBJECT_NAME].pk, is_active=True)
        initial = {'product': context[self.CONTEXT_OBJECT_NAME].pk}
        if self.request.user.is_authenticated:
            initial['author'] = self.request.user.username
            initial['is_anonimous'] = False
            form_class = UserCommentForm
        else:
            initial['author'] = Comment.ANONIMOUS_NAME
            initial['is_anonimous'] = True
            form_class = GuestCommentForm

        form = form_class(initial=initial)
        if self.request.method == 'POST':
            c_form = form_class(self.request.POST)
            if c_form.is_valid():
                c_form.save()
                messages.add_message(self.request, messages.SUCCESS, 'Комментарий добавлен')
                if c_form.cleaned_data['is_claim']:
                    messages.add_message(self.request, messages.INFO, 'Информация с Вашей жалобой отправлена в службу контроля качества')

            else:
                form = c_form
                messages.add_message(self.request, messages.WARNING, 'Комментарий не добавлен')

        context.update({'comments': comments, 'comment_form': form})
        return context

    post = DetailView.get


def any_page(request, url):
    try:
        template = get_template(f'main/{url}.html')
        return HttpResponse(template.render(request=request))
    except TemplateDoesNotExist:
        return HttpResponseNotFound(request)


@login_required
def favorite_toggle(request, pk):
    product = Product.objects.get(pk=pk)
    productrelated, _ = UserProductRelated.objects.get_or_create(product=product, user=request.user)
    productrelated.is_favorit = not productrelated.is_favorit
    productrelated.save()

    if (next := request.GET.get('next')):
        return redirect(next)
    elif (path := request.META.get('HTTP_REFERER')):
        return redirect(path)
    else:
        return redirect('main:index')
    

class FavoriteProductsView(LoginRequiredMixin, ListView):
    template_name = 'main/favorite_products.html'
    context_object_name = 'favorite_products'
    
    def get_queryset(self):
        queryset = Product.objects.filter(userproductrelated__user=self.request.user.pk, userproductrelated__is_favorit__exact=True)
        return queryset


@user_permission_test(user_is_staff)
def product_create_view(request):
    if request.method == 'POST':
        product_form = CreateProductForm(data=request.POST, files=request.FILES)
        if product_form.is_valid():
            product = product_form.save()
            image_form = AdditionalImageFormSet(data=request.POST, files=request.FILES, instance=product)
            characteristic_form = SelectCharacteristicFormSet(data=request.POST, instance=product)
            if characteristic_form.is_valid():
                characteristic_form.save()
            if image_form.is_valid():
                image_form.save()
                messages.add_message(request, messages.SUCCESS, 'Товар добавлен')
            else:
                messages.add_message(request, messages.SUCCESS, 'Товар добавлен без изображений поскольку основное изображение не выбрано')
            return redirect('main:detail', pk=product.pk)

        messages.add_message(request, messages.WARNING, 'Товар не добавлен')
    else:
        product_form = CreateProductForm()
        image_form = AdditionalImageFormSet()
        characteristic_form = SelectCharacteristicFormSet()

    context = {
        'product_form': product_form,
        'image_form': image_form,
        'characteristic_form': characteristic_form,
    }

    return render(request, 'main/product_create.html', context)


@user_permission_test(user_is_staff)
def product_edit_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product_form = EditProductForm(data=request.POST, files=request.FILES, instance=product)
        if product_form.is_valid():
            product_form.save()
            image_form = AdditionalImageFormSet(data=request.POST, files=request.FILES, instance=product)
            characteristic_form = SelectCharacteristicFormSet(data=request.POST, instance=product)
            if characteristic_form.is_valid():
                characteristic_form.save()
            if image_form.is_valid():
                image_form.save()
                messages.add_message(request, messages.SUCCESS, 'Товар изменен')
            else:
                messages.add_message(request, messages.SUCCESS, 'Товар добавлен без изображений поскольку основное изображение не выбрано')
            return redirect('main:detail', pk=product.pk)

        messages.add_message(request, messages.WARNING, 'Товар не изменен')
    else:
        product_form = EditProductForm(instance=product)
        image_form = AdditionalImageFormSet(instance=product)
        characteristic_form = SelectCharacteristicFormSet(instance=product)

    context = {
        'product_form': product_form,
        'image_form': image_form,
        'characteristic_form': characteristic_form,
    }

    return render(request, 'main/product_edit.html', context)


@user_permission_test(user_is_staff)
def product_del_view(request, pk):

furniture_shop_backend/main/templates/main/actions.html
{% extends 'layout/base.html' %} {% load static %} {% load bootstrap5 %} 

{% block title %}Акции{% endblock title %}

{% block content %}
<h3>Внимание акция!</h3>
<p>Купите три наименования товаров и пользуйтесь с удовольствием!</p>
{% endblock content %}

furniture_shop_backend/main/templates/main/contacts.html
{% extends 'layout/base.html' %} {% load static %} {% load bootstrap5 %} 

{% block title %}Контакты{% endblock title %}

{% block content %}
<h3>Контактная информация</h3>
<p>Адрес: г.Воронеж, ул.Лизюкова, рядом с котёнком</p>
<p>Рабочий телефон: +7(999)111-33-44</p>
{% endblock content %}

furniture_shop_backend/main/templates/main/detail.html
{% extends 'layout/base.html' %} {% load static %} {% load bootstrap5 %} 

{% load store_tags %} 


{% block title %}
{{ item.title }}
{% endblock title %}

{% block content %}

<div class="d-inline-block">
  <div class="card mb-3"  style="max-width: 800px;">
    <div class="card-body">
      {% url 'main:favorite_toggle' pk=item.pk as url %}
      {% favorite_widget item href=url favorite_class="favorite" %}

      <small><p class="card-text">{{ item.category.title }}</p></small>
      <h4 class="card-title">{{ item.title }}</h4>
      <p class="card-text">
        <small class="text-muted">Цена: </small>{{ item.price }} руб.
      </p>
      <p class="card-text">
        <small class="text-muted">
          {% if item.count %} в наличии {{ item.count }} шт. {% else %}
          отсутствует в наличии. доступно под заказ {% endif %}
        </small>
      </p>
    </div>
  </div>

  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button
        class="nav-link active"
        id="description-tab"
        data-bs-toggle="tab"
        data-bs-target="#description-tab-pane"
        type="button"
        role="tab"
        aria-controls="description-tab-pane"
        aria-selected="true"
      >
        Описание
      </button>
    </li>
    <li class="nav-item" role="presentation">
      <button
        class="nav-link"
        id="characteristic-tab"
        data-bs-toggle="tab"
        data-bs-target="#characteristic-tab-pane"
        type="button"
        role="tab"
        aria-controls="characteristic-tab-pane"
        aria-selected="false"
      >
        Характеристики
      </button>
    </li>
    <li class="nav-item" role="presentation">
        <button
          class="nav-link"
          id="galary-tab"
          data-bs-toggle="tab"
          data-bs-target="#galary-tab-pane"
          type="button"
          role="tab"
          aria-controls="galary-tab-pane"
          aria-selected="false"
        >
          Фотографии
        </button>
      </li>
  </ul>

  <div class="tab-content" id="myTabContent" style="max-width: 800px;">
    <div
      class="tab-pane fade show active"
      id="description-tab-pane"
      role="tabpanel"
      aria-labelledby="description-tab"
      tabindex="0"
    >
      {{ item.description }}
    </div>
    <div
      class="tab-pane fade"
      id="characteristic-tab-pane"
      role="tabpanel"
      aria-labelledby="characteristic-tab"
      tabindex="0"
    >
      <p class="card-text">Характеристики:</p>

      <ul>
        {% characteristics_as_ul item.characts_to_public %}
      </ul>
    </div>

    <div
      class="tab-pane fade"
      id="galary-tab-pane"
      role="tabpanel"
      aria-labelledby="galary-tab"
      tabindex="0"
    >


    <div id="image-carousel" class="carousel carousel-dark slide" data-bs-theme="dark">
      <div class="carousel-inner">
        {% if item.image %}
          <div class="carousel-item active">
            <img src="{{ item.image.url }}" class="d-block w-100">
          </div>
          {% else %}
          <div class="carousel-item active">
            <img src="{% static image_stub %}" class="d-block w-100">
          </div>
          {% endif %}

        {% for image in additional_images %}
        <div class="carousel-item">
          <img src="{{ image.image.url }}" class="d-block w-100">
        </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#image-carousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Предыдущий</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#image-carousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Следующий</span>
      </button>
    </div>



    </div>
  </div>
  <div class="btn-group" role="group" aria-label="Basic outlined example">
    {% if request.META.HTTP_REFERER %} 
    {% bootstrap_button "Вернуться обратно" button_type="link" button_class="btn-outline-primary" href=request.META.HTTP_REFERER size="small" %} 
    {% else %} 
    {% url 'main:index' as url %} 
    {% bootstrap_button "Вернуться обратно" button_type="link" button_class="btn-outline-primary" href=url size="small" %} 
    {% endif %} 
    {% url 'cart:cart_add' pk=item.pk as url_cart_add %}
    {% bootstrap_button "Добавить в корзину" button_type="link" button_class="btn-outline-primary" href=url_cart_add size="small" %}
    {% if user.is_staff  %}

    {% url 'main:product_create' as url_create %} 
    {% url 'main:product_edit' pk=item.pk as url_edit %} 
    {% bootstrap_button "Редактировать товар" button_type="link" button_class="btn-outline-primary" href=url_edit size="small" %}
    {% bootstrap_button "Добавить новый товар" button_type="link" button_class="btn-outline-primary" href=url_create size="small" %}
    <form method='post' action="{% url 'main:product_delete' pk=item.pk %}">
      {% csrf_token %}
      {% bootstrap_button "Удалить" button_type="submit" button_class="btn-outline-primary" size="small" %}
    </form>
    {% endif %}
  </div>
</div>

<h4 class="mt-5">Новый комментарий</h4>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form comment_form layout='horisontal' %}
    {% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% if comments %}
<div class="mt-5">
    {% for comment in comments %}
    <div class="my-2 p-2 border">
        <h5>{{ comment.author }}</h5>
        <p>{{ comment.content }}</p>
        <p class="text-right font-italic">{{ comment.created_at }}</p>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock content %}

furniture_shop_backend/main/templates/main/favorite_products.html
{% extends 'layout/base.html' %}

{% load static %}
{% load bootstrap5 %}


{% block title %}Список избранного{% endblock title %}

{% block content %}

<div class="d-inline-block">

<h3>Товары в списке избранного</h3>


<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Товар</th>
        <th scope="col">Фото</th>
        <th scope="col">Цена</th>
        <th scope="col">Валюта</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>

{% for item in favorite_products %}

<tr>
    <th scope="row">{{ forloop.counter }}</th>
    <td>
      <a href="{% url 'main:detail' pk=item.pk %}">
        {{ item.title }}
      </a>
    </td>
    <td>
      <a href="{% url 'main:detail' pk=item.pk %}">
        {% if item.image %}
        <img src="{{ item.image.url }}" class="img-fluid rounded-start main-image">
        {% else %}
        <img src="{% static image_stub %}" class="img-fluid rounded-start main-image">
        {% endif %}
      </a>
    </td>
    <td>{{item.price}}</td>
    <td>руб.</td>
    <td>
      {% url 'main:favorite_toggle' pk=item.pk as url_favorite_toggle %}
        {% url 'cart:cart_add' pk=item.pk as url_cart_add %}
        {% bootstrap_button "Добавить в коризу" button_type="link" href=url_cart_add size="small" %}
        {% bootstrap_button "Удалить из избанного" button_type="link" href=url_favorite_toggle size="small" %}
    </td>
  </tr>

{% endfor %}

</tbody>
</table>

{% endblock content %}

furniture_shop_backend/main/templates/main/index.html
{% extends 'layout/base.html' %}

{% load static %}
{% load bootstrap5 %}
{% load store_tags %}

{% block title %}
{% if category %}
{{ category }} - 
{% endif %}Магазин
{% endblock title %}


{% block content %}

<div class="d-inline-block">

<h3>Товары, представленные в магазине </h1>

{% if category %}
<h5>Категория: {{ category }}</h5>
{% endif %}

{% for item in store %}

{% url "main:detail" pk=item.pk as url_detail %}

<div class="card mb-3" style="max-width: 800px;">
    <div class="row g-0">
      <div class="col-md-6">
        <a href="{{ url_detail }}">
          {% if item.image %}
            <img src="{{ item.image.url }}" class="img-fluid rounded-start main-image">
          {% else %}
            <img src="{% static image_stub %}" class="img-fluid rounded-start main-image">
          {% endif %}
        </a>
      </div>
      <div class="col-md-6">
        <div class="card-body">
            {% url 'main:favorite_toggle' pk=item.pk as url %}
            {% favorite_widget item href=url favorite_class="favorite" %}
            <small><p class="card-text">{{ item.category.title }}</p></small>
            <h4 class="card-title">{{ item.title }}</h4>
          <p class="card-text">{{ item.description|truncatewords:50 }}</p>
          <p class="card-text"><small class="text-muted">Цена: </small>{{ item.price }} руб.</p>
          <p class="card-text"><small class="text-muted">
            {% if item.count %}
            в наличии
            {% else %}
            под заказ
            {% endif %}
          </small>
          </p>

          <p class="card-text">Характеристики:</p>
          
          <ul>
            {% characteristics_as_ul item.characts_to_public count=3 %}
          </ul>

          {% url "cart:cart_add" pk=item.pk as url_cart_add %}
          <div class="btn-group" role="group" aria-label="Basic outlined example">
            {% bootstrap_button "Дeтальное описание" button_type="link" button_class="btn-outline-primary" href=url_detail size="small" %}
            {% bootstrap_button "Добавить в корзину" button_type="link" button_class="btn-outline-primary" href=url_cart_add size="small" %}
          </div>
        </div>
      </div>
    </div>
  </div>

{% endfor %}

{% if is_paginated and page_obj.has_other_pages %}
{% bootstrap_pagination page_obj %}
{% endif %}

<div class="btn-group" role="group" aria-label="Basic outlined example">
  {% if user.is_staff  %}

  {% url 'main:product_create' as url_create %} 
  {% bootstrap_button "Добавить новый товар" button_type="link" button_class="btn-outline-primary" href=url_create size="small" %}

  {% endif %}
</div>


</div>


{% endblock content %}

furniture_shop_backend/main/templates/main/product_create.html
{% extends 'layout/base.html' %} {% load static %} {% load bootstrap5 %} 

{% load bootstrap5 %}

{% block title %}Добавить товар{% endblock title %}

{% block content %}

    <h3>Добавить товар</h3>
    <form method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form product_form layout='horisontal' %}
        {% bootstrap_formset image_form layout='horisontal' %}
        <h4>Характеристики:</h4>
        {% bootstrap_formset characteristic_form layout='horisontal' %}
        <input type="hidden" name="next" value="{{next}}">
        {% buttons submit='Добавить товар' %}{% endbuttons %}
    </form>
        
{% endblock content %}

furniture_shop_backend/main/templates/main/product_edit.html
{% extends 'layout/base.html' %} {% load static %} {% load bootstrap5 %} 

{% load bootstrap5 %}

{% block title %}Изменить товар{% endblock title %}

{% block content %}

    <h3>Изменить товар</h3>
    <form method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form product_form layout='horisontal' %}
        {% bootstrap_formset image_form layout='horisontal' %}
        <h4>Характеристики:</h4>
        {% bootstrap_formset characteristic_form layout='horisontal' %}
        <input type="hidden" name="next" value="{{next}}">
        {% buttons submit='Изменить товар' %}{% endbuttons %}
    </form>
        
{% endblock content %}