furniture_shop_backend/advuser/urls.py
from django.urls import path

from advuser.views import (EmailLoginView, LogoutView, 
                           SignupView, RegisterDoneView, user_activate,
                           ChangePasswordView, ChangePasswordDoneView,
                           UpdateUserView, UpdateUserDoneView)

app_name = "auth"

urlpatterns = [
    path("login/", EmailLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/activate/<str:sign>/", user_activate, name="register_activate"),
    path("register/successful/", RegisterDoneView.as_view(), name="register_done"),
    path("register/", SignupView.as_view(), name="signup"),
    path("password/change/done/", ChangePasswordDoneView.as_view(), name="password_change_done"),
    path("password/change/", ChangePasswordView.as_view(), name="password_change"),
    path("update/done/", UpdateUserDoneView.as_view(), name="update_done"),
    path("update/", UpdateUserView.as_view(), name="update"),
]

furniture_shop_backend/api/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from .views import ProductViewSet, ProductMoreDetailView, comment_CR_api

router = SimpleRouter()
router.register(r'store', ProductViewSet, basename='store')

app_name = "api"

urlpatterns = [
    *router.urls,
    path('comment/', comment_CR_api, name='comment'),
    path('detail/<int:pk>/', ProductMoreDetailView.as_view()),
]

furniture_shop_backend/cart/urls.py
from django.urls import include, path

from cart.views import cart_add, cart_view, cart_sub, cart_del, cart_clear

app_name = "cart"

urlpatterns = [
    path("add/<int:pk>/", cart_add, name="cart_add"),
    path("sub/<int:pk>/", cart_sub, name="cart_sub"),
    path("del/<int:pk>/", cart_del, name="cart_del"),
    path("clear/", cart_clear, name="cart_clear"),
    path("", cart_view, name="cart_view"),
]

furniture_shop_backend/furniture_shop/urls.py
from django.contrib import admin
from django.urls import include, path
from advuser.views import EmailLoginView
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.contrib.staticfiles.views import serve


urlpatterns = [
    path("admin/login/", EmailLoginView.as_view(template_name="advuser/admin-login.html")),
    path("admin/", admin.site.urls),
    path("auth/", include('advuser.urls')),
    path("cart/", include('cart.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path("api/", include('api.urls')),
    path('captcha/', include('captcha.urls')),
    path("", include('main.urls')),
]


if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve))) # Запрет на кеширование статики
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

furniture_shop_backend/main/urls.py
from django.urls import include, path

from .views import (any_page, IndexPageView, DetailPageView, 
                        CategoryPageView, 
                        favorite_toggle, FavoriteProductsView,
                        product_create_view,
                        product_edit_view,
                        product_del_view)


app_name = "main"

urlpatterns = [
    path("product/<int:pk>/", DetailPageView.as_view(), name="detail"),
    path("category/<int:pk>/", CategoryPageView.as_view(), name="category"),
    path("add/", product_create_view, name="product_create"),
    path("edit/<int:pk>/", product_edit_view, name="product_edit"),
    path("delete/<int:pk>/", product_del_view, name="product_delete"),
    path("favorite/<int:pk>/", favorite_toggle, name="favorite_toggle"),
    path("favorite/", FavoriteProductsView.as_view(), name="favorite_products"),
    path("<str:url>/", any_page, name="any_page"),
    path("", IndexPageView.as_view(), name="index"),
]

furniture_shop_backend/templates/layout/.inc/sidebar.html
<div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0">
  <div
    class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100"
  >
    <ul
      class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start text-white"
      id="menu"
    >
      <li class="nav-item">
        <a href="{% url 'main:index' %}" class="nav-link align-middle px-0">
          <span class="ms-1 d-sm-inline">Магазин</span>
        </a>
      </li>
      <li>
        <ul>
          {% for category in categories %} 
          {% ifchanged category.super_category.pk %}
            </ul>
          </li>
          <li>
            <a
              href="#submenu{{category.super_category.pk}}"
              data-bs-toggle="collapse"
              class="nav-link px-0 align-middle"
            >
              <span class="ms-1 d-sm-inline"
                >{{ category.super_category.title }}</span
              >
            </a>
            <ul
              class="collapse nav flex-column ms-1"
              id="submenu{{category.super_category.pk}}"
              data-bs-parent="#menu"
            >
              <li>
                <small
                  ><a
                    href="{% url 'main:category' category.super_category.pk %}"
                    class="nav-link px-0"
                    >Все {{ category.super_category.title }}</a
                  ></small
                >
              </li>

          {% endifchanged %}
          <li>
            <small
              ><a
                href="{% url 'main:category' category.pk %}"
                class="nav-link px-0"
              >
                {{ category.title }}</a
              ></small
            >
          </li>
          {% endfor %}
        </ul>
      </li>

      <li class="nav-item">
        <a
          href="{% url 'main:any_page' url='actions' %}"
          class="nav-link align-middle px-0"
        >
          <span class="ms-1 d-sm-inline">АКЦИИ!</span>
        </a>
      </li>
      <li class="nav-item">
        <a
          href="{% url 'main:any_page' url='contacts' %}"
          class="nav-link align-middle px-0"
        >
          <span class="ms-1 d-sm-inline">КОНТАКТЫ</span>
        </a>
      </li>
    </ul>
  </div>
</div>

furniture_shop_backend/templates/layout/.inc/topmenu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <ul class="col navbar-nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auth:signup' %}"
            >Регистрация</a
          >
        </li>
        {% if user.is_authenticated %}
        <div class="btn-group">
          <li class="nav-item dropdown">
            <span
              class="nav-link dropdown-toggle"
              data-bs-toggle="dropdown"
              href="#"
              role="button"
              aria-expanded="false"
              id="dropdownMenuButton1"
              data-display="static"
              >Профиль
            </span>
            <ul
              class="dropdown-menu dropdown-menu-right dropdown-menu-end"
              aria-labelledby="dropdownMenuButton1"
            >
                {% if not user.is_activated%}
                <div class="alert alert-warning py-3 my-0">{{user.email}}</div>
                <div class="alert alert-danger py-0 mt-0"><small>Учетная запись не активирована</small></div>
                {% else %}
                <div class="alert alert-primary py-3 mt-0">{{user.email}}</div>
                {% endif %}
              <li>
                <a
                  class="dropdown-item"
                  href="{% url 'cart:cart_view' %}"
                  >Товары в корзине</a
                >
              </li>
              <li>
                <a
                  class="dropdown-item"
                  href="{% url 'main:favorite_products' %}"
                  >Избранные товары</a
                >
              </li>
              <li><hr class="dropdown-divider" /></li>

              <li>
                <a class="dropdown-item" href="{% url 'auth:update' %}"
                  >Изменить личные данные</a
                >
              </li>
              <li>
                <a
                  class="dropdown-item"
                  href="{% url 'auth:password_change' %}"
                  >Изменить пароль</a
                >
              </li>
              <li><hr class="dropdown-divider" /></li>
              <li>
                <a class="dropdown-item" href="{% url 'auth:logout' %}"
                  >Выйти</a
                >
              </li>
            </ul>
          </li>
        </div>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auth:login' %}">Вход</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>